[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Pointfoot-Isaac Lab Extension"
author = "Xiong hongwei"
maintainer = "Xiong hongwei"
description="Pointfoot Extension for Isaac Lab"
repository = "https://github.com/Andy-xiong6/pointfoot-IsaacLabExtension.git"
keywords = ["extension", "isaaclab", "pointfoot", "locomotion"]

[dependencies]
"omni.isaac.lab" = {}
"omni.isaac.lab_assets" = {}
"omni.isaac.lab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "pointfoot"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
